name: build
on: [push]

jobs:
  build:
    name: build
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          registry: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: yarn
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          tags: ${{ secrets.DOCKER_HOST }}/${{ secrets.DOCKER_REPO }}/${{ github.event.repository.name }}:2021-04-22
          push: true
