name: build
on: [push]

jobs:
  build:
    name: build
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          registry: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          yarn && docker/build.sh && docker/push.sh
        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}

